name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Installing MinGW
      uses: egor-tensin/setup-mingw@v2
      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Compile Separated Values
      run: dir
      shell: cmd
