name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installation
      uses: egor-tensin/setup-mingw@v1
      
    - name: Check
      run: g++ --version
      
    - name: Compile Separated Values
      working-directory: ./CSV/sv
      shell: cmd
      run: |
        g++ -c sv.cpp -o SeparatedValues -Ofast -std=gnu++17 -Wall -Wextra -pedantic -Werror -Wfatal-errors -DBUILDING_DLL=1
        ar r SeparatedValues.a SeparatedValues
        ranlib SeparatedValues.a
    - name: Compile Comma-Separated Values
      working-directory: ./CSV
      shell: cmd
      run: |
        g++ -c csv.cpp -o csv.o -Ofast -std=gnu++17 -Wall -Wextra -Wpedantic -Werror -Wfatal-errors -DBUILDING_DLL=1
        g++ -shared csv.o -o CSV.dll -static-libgcc SV/SeparatedValues.a -s
