name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installation
      uses: egor-tensin/setup-mingw@v1
      
    - name: Check
      run: g++ --version
      
    - name: Compile Separated Values
      working-directory: ./CSV/sv
      run: |
        g++ -c *.cpp -o SeparatedValues -Ofast -std=gnu++17 -Wall -Wextra -pedantic -Werror -Wfatal-errors -DBUILDING_DLL=1
        ar r SeparatedValues.a SeparatedValues
        ranlib SeparatedValues.a
      shell: sh
    - name: Compile Comma-Separated Values
      working-directory: ./CSV
      run: |
        g++ -c *.cpp -o csv.o -Ofast -std=gnu++11 -Wall -Wextra -pedantic -Werror -Wfatal-errors -DBUILDING_DLL=1 -xc++
        g++ -shared csv.o -o CSV.dll -static-libgcc ./SV/SeparatedValues.a -s -Wl,--output-def,libCSV.def,--out-implib,libCSV.a,--add-stdcall-alias
      shell: sh
